---
title:
author: "Brendan Graham"
date: "March 26, 2016"
output: html_document
---

####2. 

```{r, echo = FALSE, fig.align='center'}
library(astsa)
w <- seq(from = -100, to = 100, by=.001)

plot(w, (1-(.5*cos(6*pi*w))-(cos(4*pi*w))), type = "l", xlim=c(-.6, .6), main = "Spectral Density Plot for #2")


```


####4. 

```{r, echo=FALSE, fig.align='center'}
library(astsa)

arma.spec(ma = c(.999,.998), var.noise = 1, log="no", n.freq=500, main = "Spectral Density for #4")

```


####5.
a) The spectral density plot below shows spikes around 0 and about 0.33, which suggests the the process will show oscillatory behavior with a period of about 3.

```{r, echo = FALSE, fig.align='center'}

library(astsa)

arma.spec(ar = c(0, 0, .99), log="no", main = "Spectral Density Plot")


```


b) The time series plot below indicate that after about every 3 points the series repeats after 3 points, which agrees with the spectral density plot
```{r, echo = FALSE, fig.align='center'}
library(astsa)
ts_AR <- arima.sim(n=100, list(ar=c(0, 0, .99)))

plot(ts_AR, type = "o", ylab = "simulated process", main = "Time Series Plot")
```

